### ISSUE TITLE
API not working?

### ISSUE THREAD

**Issue by wastlnd** [BarbossHack/RiseupVPN-OpenVPN#1]
I have just tried the genetate.sh script but it hangs without generating the configuration file. I'm afraid that the black riseupvpn API is no longer working.

**Comment by BarbossHack** [comment]
Indeed, Riseup VPN (not only the API) seems to be down for a few weeks... (2 months in fact https://0xacab.org/leap/bitmask-vpn/-/issues/742 )

**Comment by wastlnd** [comment]
Yet I tried it yesterday and it worked flawlessly, maybe it's up and down randomly.
