### ISSUE TITLE
Run as user?

### ISSUE THREAD

**Issue by wastlnd** [BarbossHack/RiseupVPN-OpenVPN#2]
I would like to put the command "openvpn --config riseup-ovpn.conf" in my openbox autostart file to not type it at every boot, but, of course, I can't put it with sudo. Is there a way to run the generated conf file as user?TIA.

**Comment by BarbossHack** [comment]
I think the best way is to setup a systemd service that will start openvpn at boot https://community.openvpn.net/openvpn/wiki/OpenVPN-systemd-use

**Comment by wastlnd** [comment]
Thank you, actually I don't use systemd but s6/66, I will ask to my distro how to setup a proper service.
