### ISSUE TITLE
Temporary fix until author fixes issues with script

### ISSUE THREAD

**Issue by x4740N** [BarbossHack/RiseupVPN-OpenVPN#7]
```
#!/bin/bash

set -eu

# Verbose mode
if [ $# == 1 ] && [ "$1" == "-v" ]; then
    VERBOSE=1
    set -x
fi

OVPN_CONF=riseup-ovpn.conf

echo -e "\e[30mPlease wait, riseup API is slow...\e[0m"

# Download new VPN client certs (private and public keys)
# Orignal Timeout = 5
#key_cert=$(curl ${VERBOSE:+-v} -sS --fail --connect-timeout 10 --retry 5 https://api.black.riseup.net/3/cert)
#below command has timeout removed to solve timeout issue and silence removed to give visual feedback
#key_cert=$(curl ${VERBOSE:+-v} --fail --retry 5 https://api.black.riseup.net/3/cert)
key_cert=$(curl ${VERBOSE:+-v} --fail --retry 5 https://black.riseup.net/3/cert)

# Copy the sample openvpn conf
cp riseup-ovpn.sample.conf $OVPN_CONF
sed -i 's/^remote .*$//g' $OVPN_CONF
echo -e "\n<key>\n$key_cert\n</key>" >>$OVPN_CONF
echo -e "\n<cert>\n$key_cert\n</cert>" >>$OVPN_CONF

# Get the VPN IP list, and add them to openvpn conf
# Orignal Timeout = 5
#gateways=$(curl ${VERBOSE:+-v} -sS --fail --connect-timeout 10 --retry 5 https://api.black.riseup.net/3/config/eip-service.json | jq '.gateways')
#below command has timeout removed to solve timeout issue and silence removed to give visual feedback
gateways=$(curl ${VERBOSE:+-v} --fail --retry 5 https://api.black.riseup.net/3/config/eip-service.json | jq '.gateways')

for gateway_b64 in $(echo "$gateways" | jq -r '.[] | @base64'); do

    gateway=$(echo $gateway_b64 | base64 --decode)
    ip_address=$(echo $gateway | jq -r '.ip_address')
    host=$(echo $gateway | jq -r '.host')
    location=$(echo $gateway | jq -r '.location')
    ports=$(echo $gateway | jq -r '.capabilities.transport[] | select( .type | contains("openvpn")) | .ports[]')

    for port in $ports; do
        sed -i "/^remote-random$/i remote $ip_address $port # $host ($location)" $OVPN_CONF
    done
done

echo -e "\e[42m[+]\e[0m OpenVPN conf was created with success, you can now run:"
echo "sudo openvpn --config $OVPN_CONF"

```

This fixes the curl 404 error.

 for those that notice the timeout removed it is from a previous fix if mine for when riseup was slower than the timeout the author set, Riseholme can be slower than the authors set timeout even on fast Internet connections depending on where you are how your Internet Is routed

**Comment by BarbossHack** [comment]
For the silent option (-sS), you can run the script in verbose mode
```bash
./generate.sh -v
```

For the connect-timeout, your network may be veeery slow to not be able to make the TCP handshake within 10 seconds... Could you please share the full output of the following command ? It will be very helpfull for me to know how to properly fix this issue :pray:  (you can send the output to barbossh4ck@protonmail.com if you want)
```bash
time curl -v --retry 5 -H "Accept: text/html" https://api.black.riseup.net/3/cert
```

Thank you!

**Comment by BarbossHack** [comment]
> also on macOS it needs to be modified a little bit
> 
> `sed -i '' -e "/^remote-random$/i\\ remote $ip_address $port # $host ($location)" $OVPN_CONF`

Can you give me the full output when running the original script on mac ? run it in verbose mode : 
```bash
./generate.sh -vvv
```

**Comment by BarbossHack** [comment]
MacOS indeed does not use a "GNU" sed... so the fix you provided does not work on Linux unfortunately. According to [this issue](https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux/4247319#4247319) it is not possible to have something compatible with both MacOS **_and_** Linux

Please try to clone the new `darwin` and to install gnu-sed
```
brew install gnu-sed

git clone https://github.com/BarbossHack/RiseupVPN-OpenVPN -b darwin
cd RiseupVPN-OpenVPN/
./generate.sh
```
